version: "3.8"
services:
  web:
    build: .
    ports:
      - 80:8080
    environment:
      - PORT=8080
      - APIKEY=2TINDEVOPS
      - CONNECTIONSTRING=mongodb://mongo:27017/devops
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo
    ports:
      - 27017:27017
