apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  selector:
    matchLabels:
      app: angular-app
  replicas: 3
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app-backend
          image: architius/backend-image:1
          ports:
            - containerPort: 8080
        - name: angular-app-frontend
          image: architius/frontend-image:1
          ports:
            - containerPort: 8080
